name: Feature Branch Merge Workflow

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the project
    - name: Build project
      run: npm run build

    # Run unit tests
    - name: Run tests
      run: npm test

  merge-to-main:
    name: Merge to Main
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success()

    steps:
    # Checkout the code with full history
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Configure git user
    - name: Configure git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Merge dev into main
    - name: Merge dev into main
      run: |
        git checkout main
        git merge dev --no-edit

    # Push the changes
    - name: Push changes
      run: |
        git push origin main
